import { describe, it, expect } from 'vitest';
import { strFromU8, strToU8, unzipSync, zipSync } from 'fflate';
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { analyzeWordTemplate, readTemplate } from '../../src/document/templates/WordTemplateAnalyzer';
import { WordTemplateStore } from '../../src/main/export/WordTemplateStore';
import { renderDocx } from '../../src/document/export/DocxRenderer';
import { DEFAULT_WRITING_APPEARANCE } from '../../src/renderer/preferences/WritingAppearance';
import { TEMPLATE_ROLES, type TemplateRole } from '../../src/shared/wordTemplate';
import { attr, child, elements, parseXml } from '../../src/document/templates/WordXml';
import { resolvePart } from '../../src/document/templates/WordTemplateRenderer';
import { modelFor } from './helpers';
import { templatePng, wordTemplateFixture } from './wordTemplateFixtures';

const candidate = (p: ReturnType<typeof analyzeWordTemplate>, role: TemplateRole) => p.candidates.find(c => c.id === p.mappings[role].candidateId)!;
function edited(change: (files: Record<string, Uint8Array>) => void, kind: 'formal' | 'technical' | 'direct' = 'formal') { const files = unzipSync(wordTemplateFixture(kind)); change(files); return zipSync(files); }
const profileFor = (bytes: Uint8Array) => { const p = analyzeWordTemplate(bytes,'验收模板','test'); p.confirmed = true; p.warningsAccepted = true; return p; };
const source = '# 新报告\n\n中文 English **加粗** *斜体*，参见 [@fig:f] [@eq:e] [@tbl:t]。\n\n# 研究背景 {#sec:s}\n\n## 方法\n\n1. 第一个项目\n2. 第二个项目\n   - 嵌套项\n\n> 引用\n\n![实验装置](image.png){#fig:f}\n\n表 1 数据说明\n\n| 参数 | 数值 |\n| --- | ---: |\n| 响应 | $x^2$ |\n{#tbl:t}\n\n$$\nE=mc^2\n$$\n{#eq:e}\n\n[外部链接](https://example.com)\n\n结束。';
async function exportWith(bytes = wordTemplateFixture(), value = source, profile = profileFor(bytes)) {
  const model = modelFor(value), snapshot = JSON.stringify(model.root);
  const result = await renderDocx({ model, appearance: DEFAULT_WRITING_APPEARANCE, template: { bytes, profile }, signal: new AbortController().signal, resources: { read: async () => ({ bytes: templatePng, mime: 'image/png' }) } }, { image: async () => templatePng, formula: async () => templatePng });
  expect(JSON.stringify(model.root)).toBe(snapshot);
  const files = unzipSync(result.bytes), part = (path: string) => strFromU8(files[path]);
  return { ...result, files, part, doc: parseXml(part('word/document.xml')), styles: parseXml(part('word/styles.xml')) };
}

describe('Word template analysis', () => {
  it.each(['formal','technical','direct'] as const)('identifies %s body and page without inventing certainty', kind => {
    const p = analyzeWordTemplate(wordTemplateFixture(kind),kind,'test'); expect(candidate(p,'body').summary).toContain('中文'); expect(p.page.left).toBe(1701); expect(p.page.summary).toContain('纵向');
    expect(p.confirmed).toBe(false); if (kind === 'direct') { expect(candidate(p,'body').source).toBe('sample'); expect(p.warnings.join()).toContain('直接格式'); }
  });
  it('maps all Word Heading levels and a separate Title style', () => {
    const p = profileFor(wordTemplateFixture()); for (let i=1;i<=6;i++) { expect(candidate(p,`heading${i}` as TemplateRole).styleId).toBe(`Heading${i}`); expect(p.mappings[`heading${i}` as TemplateRole].confidence).toBe('high'); } expect(candidate(p,'title').styleId).toBe('Title');
  });
  it('distinguishes figure and table captions and retains table evidence', () => { const p = profileFor(wordTemplateFixture()); expect(candidate(p,'figureCaption').styleId).toBe('FigureCaption'); expect(candidate(p,'tableCaption').styleId).toBe('TableCaption'); expect(p.tableSummary).toContain('ReportTable'); });
  it('extracts mixed language fonts, spacing and first-line indentation', () => { const p = profileFor(wordTemplateFixture('technical')), c = candidate(p,'body'); expect(c.summary).toContain('仿宋'); expect(c.summary).toContain('Times New Roman'); expect(c.summary).toContain('12 pt'); expect(c.summary).toContain('1.50 倍'); expect(c.summary).toContain('24 pt'); });
  it('infers direct-format titles and heading levels with medium confidence', () => { const p = profileFor(wordTemplateFixture('direct')); expect(candidate(p,'title').sample).toContain('非规范'); expect(candidate(p,'heading1').sample).toContain('一、'); expect(candidate(p,'heading2').sample).toContain('1.1'); expect(p.mappings.heading1.confidence).toBe('medium'); });
  it('maps captions sharing a direct-format group to both caption roles', () => { const p=profileFor(wordTemplateFixture('direct')); expect(p.mappings.figureCaption.candidateId).toBe(p.mappings.tableCaption.candidateId); expect(p.mappings.tableCaption.candidateId).not.toBeNull(); expect(p.mappings.tableCaption.confidence).toBe('medium'); });
  it('recognizes Chinese and English fonts when separate runs define them', () => {
    const bytes=edited(f=>{const xml=strFromU8(f['word/document.xml']); f['word/document.xml']=strToU8(xml.replaceAll('这是一段中文正文排版样本。Mixed language content demonstrates Latin typography and paragraph spacing. 模板中的正文应保持可编辑。','中文段落样本中文段落样本</w:t></w:r><w:r><w:rPr><w:rFonts w:ascii="Georgia" w:hAnsi="Georgia"/></w:rPr><w:t>English content'));});
    expect(candidate(profileFor(bytes),'body').summary).toContain('Georgia');
  });
  it('resolves Chinese and Latin theme fonts for the readable summary', () => {
    const bytes=edited(f=>{ f['word/theme/theme1.xml']=strToU8('<a:theme xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"><a:themeElements><a:fontScheme name="Test"><a:minorFont><a:latin typeface="Georgia"/><a:ea typeface=""/><a:font script="Hans" typeface="等线"/></a:minorFont></a:fontScheme></a:themeElements></a:theme>'); f['word/styles.xml']=strToU8(strFromU8(f['word/styles.xml']).replaceAll('w:eastAsia="宋体" w:ascii="Arial" w:hAnsi="Arial"','w:eastAsiaTheme="minorEastAsia" w:asciiTheme="minorHAnsi" w:hAnsiTheme="minorHAnsi"')); });
    expect(candidate(profileFor(bytes),'body').summary).toContain('Georgia'); expect(candidate(profileFor(bytes),'body').summary).toContain('等线');
  });
  it('does not let a short bold span replace the dominant body run', () => {
    const bytes = edited(f => { f['word/document.xml'] = strToU8(strFromU8(f['word/document.xml']).replace('这是一段', '</w:t></w:r><w:r><w:rPr><w:b/></w:rPr><w:t>强调</w:t></w:r><w:r><w:t>这是一段')); });
    const p = profileFor(bytes); expect(candidate(p,'body').run).not.toContain('<w:b');
  });
  it('keeps Chinese and Latin font attributes inherited independently', () => { const p = profileFor(wordTemplateFixture()); const c = candidate(p,'title'); expect(c.run).toContain('w:eastAsia="黑体"'); expect(c.run).toContain('w:ascii="Arial"'); });
  it('reports native page fields and preserved header/footer text', () => { const p = profileFor(wordTemplateFixture()); expect(p.runningMatter.join()).toContain('正式报告'); expect(p.runningMatter.join()).toContain('原生页码字段'); });
  it('marks missing definitions and unresolved roles as uncertain', () => { const p = profileFor(wordTemplateFixture('direct', { 'word/styles.xml': null })); expect(p.warnings.join()).toContain('缺少样式定义'); expect(p.mappings.heading6).toMatchObject({ candidateId: null, confidence:'low' }); });
  it('survives cyclic style inheritance with a warning', () => {
    const bytes = edited(f => { f['word/styles.xml'] = strToU8(strFromU8(f['word/styles.xml']).replace('<w:name w:val="Normal"/>','<w:name w:val="Normal"/><w:basedOn w:val="Heading1"/>')); }); expect(profileFor(bytes).warnings.join()).toContain('循环');
  });
  it('warns for complex sections, columns and text boxes before confirmation', () => {
    const bytes = edited(f => { f['word/document.xml'] = strToU8(strFromU8(f['word/document.xml']).replace('<w:body>', '<w:body><w:p><w:pPr><w:sectPr><w:cols w:num="2"/></w:sectPr></w:pPr><w:r><w:txbxContent/></w:r></w:p>')); }); const p = profileFor(bytes); expect(p.warnings.join()).toMatch(/分节/); expect(p.warnings.join()).toMatch(/多栏/); expect(p.warnings.join()).toMatch(/文本框/);
  });
  it('recognizes landscape pages', () => { const bytes = edited(f => { f['word/document.xml'] = strToU8(strFromU8(f['word/document.xml']).replace('w:w="11906" w:h="16838"','w:w="16838" w:h="11906" w:orient="landscape"')); }); expect(profileFor(bytes).page.summary).toContain('横向'); });
  it.each(['word/vbaProject.bin','word/activeX/object.bin','word/embeddings/object.bin'])('rejects active parts %s', path => { expect(() => profileFor(wordTemplateFixture('formal', { [path]: new Uint8Array([1]) }))).toThrow(/宏/); });
  it('rejects broken XML and entity declarations', () => { expect(() => profileFor(wordTemplateFixture('formal', { 'word/styles.xml': '<broken' }))).toThrow(); expect(() => profileFor(wordTemplateFixture('formal', { 'word/styles.xml': '<!DOCTYPE x><x/>' }))).toThrow(/实体/); });
  it('rejects broken running matter before confirming or exporting', () => { expect(()=>profileFor(wordTemplateFixture('formal',{'word/header1.xml':null}))).toThrow(/页眉页脚/); });
  it('rejects old DOC, absent main part and oversized expansion', () => { expect(() => readTemplate(new Uint8Array([1,2,3]))).toThrow(); expect(() => readTemplate(wordTemplateFixture('formal', { 'word/document.xml': null }))).toThrow(); const bytes=wordTemplateFixture(), view=new DataView(bytes.buffer); for(let i=0;i+46<bytes.length;i++) if(view.getUint32(i,true)===0x02014b50) { view.setUint32(i+24,101*1024*1024,true); break; } expect(() => readTemplate(bytes)).toThrow(/解压/); });
});

describe('editable Word template export', () => {
  it.each(['formal','technical','direct'] as const)('exports %s as a complete native Word package', async kind => { const o = await exportWith(wordTemplateFixture(kind)); expect(elements(o.doc,'tbl')).toHaveLength(1); expect(elements(o.doc,'tc')).toHaveLength(4); expect(o.part('word/document.xml')).toContain('<m:oMath'); expect(o.part('word/document.xml')).toContain('结束。'); expect(o.part('word/document.xml')).not.toContain('模板中的正文'); for(const [path,data] of Object.entries(o.files)) if(/\.xml$|\.rels$/.test(path)) expect(() => parseXml(strFromU8(data))).not.toThrow(); });
  it('preserves source template parts and avoids generated header/footer or old body leakage', async () => { const bytes=wordTemplateFixture(), original=unzipSync(bytes), o=await exportWith(bytes); expect(o.files['word/header1.xml']).toEqual(original['word/header1.xml']); expect(o.files['word/footer1.xml']).toEqual(original['word/footer1.xml']); expect(o.part('word/document.xml')).not.toContain('这是一段中文正文排版样本'); expect(o.part('word/_rels/document.xml.rels')).toContain('tplHeader'); });
  it('uses template page rules and paragraph formatting instead of the preset overrides', async () => { const o=await exportWith(wordTemplateFixture('technical')); expect(attr(elements(o.doc,'pgMar')[0],'left')).toBe('1701'); const bodyStyle=elements(o.styles,'style').find(s => attr(s,'styleId')==='FolioExportbody')!; expect(attr(elements(bodyStyle,'rFonts')[0],'eastAsia')).toBe('仿宋'); expect(attr(elements(bodyStyle,'spacing')[0],'lineRule')).toBe('auto'); const p=elements(o.doc,'p').find(p => p.textContent?.includes('中文 English'))!; expect(elements(p,'ind')).toHaveLength(0); expect(attr(elements(p,'pStyle')[0])).toBe('Normal'); });
  it('retains heading outline and pagination rules and differentiates caption roles', async () => { const o=await exportWith(wordTemplateFixture('technical')); const h=elements(o.styles,'style').find(n => attr(n,'styleId')==='FolioExportheading1')!; expect(elements(h,'pageBreakBefore')).toHaveLength(1); expect(attr(elements(h,'outlineLvl')[0])).toBe('0'); const s=o.part('word/document.xml'); expect(s).toContain('FigureCaption'); expect(s).toContain('TableCaption'); expect(s).toContain('Equation'); });
  it('preserves native emphasis, lists, images and external links', async () => { const o=await exportWith(); expect(elements(o.doc,'b').length).toBeGreaterThan(0); expect(elements(o.doc,'i')).toHaveLength(1); expect(elements(o.doc,'numPr').length).toBeGreaterThan(0); expect(elements(o.doc,'drawing')).toHaveLength(1); expect(o.files['word/media/folio-image1.png']).toEqual(new Uint8Array(templatePng)); expect(o.part('word/_rels/document.xml.rels')).toContain('https://example.com'); });
  it('uses clickable bookmarks for internal references and retains equation numbers', async () => { const o=await exportWith(); const links=elements(o.doc,'hyperlink').filter(n => attr(n,'anchor')); const anchors=elements(o.doc,'bookmarkStart').map(n=>attr(n,'name')); expect(links).toHaveLength(3); expect(links.every(n=>anchors.includes(attr(n,'anchor')))).toBe(true); expect(o.part('word/document.xml')).toContain('(1)'); });
  it('preserves table borders and header fill while keeping source content and column geometry editable', async () => { const o=await exportWith(); const table=elements(o.doc,'tbl')[0]; expect(attr(elements(table,'tblStyle')[0])).toBe('ReportTable'); expect(attr(elements(table,'insideV')[0])).toBe('single'); expect(attr(elements(table,'shd')[0],'fill')).toBe('E8EDF2'); expect(elements(table,'gridCol').reduce((sum,n)=>sum+Number(attr(n,'w')),0)).toBe(8788); });
  it('provides valid targets for every internal relationship', async () => { const o=await exportWith(); for(const [path,data] of Object.entries(o.files)) if(path.endsWith('.rels')) { const dom=parseXml(strFromU8(data)); const owner=path==='_rels/.rels' ? '' : path.replace('/_rels/','/').replace(/\.rels$/,''); for(const n of Array.from(dom.documentElement!.childNodes).filter(n=>n.nodeType===1) as any[]) if(n.getAttribute('TargetMode')!=='External') expect(o.files[resolvePart(owner,n.getAttribute('Target'))],path).toBeTruthy(); } });
  it('converts DOTX content type to a normal DOCX', async () => { const bytes=edited(f=> { f['[Content_Types].xml']=strToU8(strFromU8(f['[Content_Types].xml']).replace('wordprocessingml.document.main','wordprocessingml.template.main')); }); expect((await exportWith(bytes)).part('[Content_Types].xml')).toContain('wordprocessingml.document.main'); });
  it('rejects unconfirmed mappings and unacknowledged compatibility warnings', async () => { const bytes=wordTemplateFixture('direct'), p=profileFor(bytes); p.confirmed=false; await expect(exportWith(bytes,source,p)).rejects.toThrow(/确认/); p.confirmed=true; p.warningsAccepted=false; await expect(exportWith(bytes,source,p)).rejects.toThrow(/确认/); });
  it('strips editing protection and revision recording', async () => { const o=await exportWith(wordTemplateFixture('formal', { 'word/settings.xml': '<w:settings xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:documentProtection w:enforcement="1"/><w:trackRevisions/></w:settings>', 'word/_rels/document.xml.rels': strFromU8(unzipSync(wordTemplateFixture())['word/_rels/document.xml.rels']).replace('</Relationships>','<Relationship Id="settings" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/settings" Target="settings.xml"/></Relationships>') })); expect(o.part('word/settings.xml')).not.toContain('documentProtection'); expect(o.part('word/settings.xml')).not.toContain('trackRevisions'); });
  it('exports a template missing styles by synthesizing the confirmed paragraph roles', async () => { const o=await exportWith(wordTemplateFixture('direct',{'word/styles.xml':null})); expect(elements(o.doc,'tbl')).toHaveLength(1); expect(o.part('word/styles.xml')).toContain('FolioExportbody'); });
  it('uses original named styles so template STYLEREF fields keep their targets', async () => { const o=await exportWith(); const p=elements(o.doc,'p').find(n=>n.textContent?.includes('研究背景'))!; expect(attr(elements(p,'pStyle')[0])).toBe('Heading1'); });
  it('keeps fallback code left-aligned with zero first-line indentation', async () => { const o=await exportWith(wordTemplateFixture(), '```ts\nconst a = 1;\n```'); const style=elements(o.styles,'style').find(n=>attr(n,'styleId')==='FolioExportcode')!; expect(attr(elements(style,'jc')[0])).toBe('left'); expect(attr(elements(style,'ind')[0],'firstLine')).toBe('0'); });
  it('merges template numbering without ID collisions and keeps custom decimal markers', async () => {
    const bytes=edited(f=>{f['word/numbering.xml']=strToU8('<w:numbering xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:abstractNum w:abstractNumId="8"><w:lvl w:ilvl="0"><w:start w:val="1"/><w:numFmt w:val="upperRoman"/><w:lvlText w:val="%1)"/><w:lvlJc w:val="left"/><w:pPr><w:ind w:left="600" w:hanging="240"/></w:pPr></w:lvl></w:abstractNum><w:num w:numId="8"><w:abstractNumId w:val="8"/></w:num></w:numbering>');f['word/_rels/document.xml.rels']=strToU8(strFromU8(f['word/_rels/document.xml.rels']).replace('</Relationships>','<Relationship Id="nums" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/numbering" Target="numbering.xml"/></Relationships>'));});
    const o=await exportWith(bytes,'3. 项目\n4. 项目'), numbers=parseXml(o.part('word/numbering.xml'));
    const ids=elements(numbers,'num').map(n=>attr(n,'numId')); expect(new Set(ids).size).toBe(ids.length); expect(o.part('word/numbering.xml')).toContain('upperRoman'); expect(o.part('word/numbering.xml')).toContain('w:val="3"');
    for(const n of elements(o.doc,'numId')) expect(ids).toContain(attr(n));
  });
  it('preserves first and even page running rules', async () => {
    const bytes=edited(f=>{f['word/document.xml']=strToU8(strFromU8(f['word/document.xml']).replace('<w:pgNumType','<w:headerReference w:type="first" r:id="tplHeader"/><w:footerReference w:type="even" r:id="tplFooter"/><w:titlePg/><w:pgNumType'));}); const o=await exportWith(bytes); expect(elements(o.doc,'titlePg')).toHaveLength(1); expect(elements(o.doc,'headerReference').some(n=>attr(n,'type')==='first')).toBe(true);
  });
  it('retains header images and their transitive relationship graph', async () => {
    const bytes=edited(f=>{f['word/header1.xml']=strToU8(strFromU8(f['word/header1.xml']).replace('<w:hdr ', '<w:hdr xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" ').replace('</w:hdr>','<w:p><w:r><w:drawing><pic:blip xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/main" r:embed="logo"/></w:drawing></w:r></w:p></w:hdr>'));f['word/media/logo.png']=templatePng;f['word/_rels/header1.xml.rels']=strToU8('<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="logo" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="media/logo.png"/></Relationships>');});const o=await exportWith(bytes);expect(o.files['word/media/logo.png']).toEqual(new Uint8Array(templatePng));expect(o.files['word/_rels/header1.xml.rels']).toBeTruthy();
  });
  it('does not mutate source, template bytes or profile', async () => { const bytes=wordTemplateFixture('direct'), before=bytes.slice(), p=profileFor(bytes), snapshot=JSON.stringify(p); await exportWith(bytes,source,p); expect(bytes).toEqual(before); expect(JSON.stringify(p)).toBe(snapshot); });
});

describe('Word template library', () => {
  const inStore = async (run: (store: WordTemplateStore, folder: string) => Promise<void>) => { const folder=await mkdtemp(join(tmpdir(),'folio-template-test-')); try { await run(new WordTemplateStore(folder),folder); } finally { await rm(folder,{recursive:true,force:true}); } };
  const confirmation = (p: ReturnType<typeof profileFor>) => ({ id:p.id, name:'老师的报告', mappings:Object.fromEntries(Object.entries(p.mappings).map(([role,m])=>[role,m.candidateId])) as Record<TemplateRole,string|null>, warningsAccepted:true, makeDefault:true });
  it('keeps canceled imports out of the library', () => inStore(async store => { await store.import(wordTemplateFixture(),'模板'); expect((await store.list()).templates).toEqual([]); }));
  it('saves original bytes and confirmed mappings and reuses them after restart', () => inStore(async (store,folder) => { const bytes=wordTemplateFixture('direct'), p=await store.import(bytes,'模板'), confirmed=await store.confirm(confirmation(p)); const reopened=new WordTemplateStore(folder), library=await reopened.list(); expect(library.defaultId).toBe(p.id); expect(library.templates[0].name).toBe('老师的报告'); expect(new Uint8Array((await reopened.get(p.id)).bytes)).toEqual(new Uint8Array(bytes)); expect(library.templates[0].mappings).toEqual(confirmed.mappings); await exportWith(bytes,source,library.templates[0]); }));
  it('allows rename, mapping correction, default reset and removal', () => inStore(async store => { const p=await store.import(wordTemplateFixture(),'模板'), c=confirmation(p); await store.confirm(c); c.name='学院模板'; c.mappings.figureCaption=c.mappings.tableCaption; c.makeDefault=false; await store.confirm(c); expect((await store.list()).templates[0].name).toBe('学院模板'); await store.setDefault(null); expect((await store.list()).defaultId).toBeNull(); await store.remove(p.id); expect((await store.list()).templates).toHaveLength(0); }));
  it('requires body mapping, existing candidates and warning acceptance', () => inStore(async store => { const p=await store.import(wordTemplateFixture('direct'),'模板'), c=confirmation(p); c.warningsAccepted=false; await expect(store.confirm(c)).rejects.toThrow(/兼容性/); c.warningsAccepted=true; c.mappings.body=null; await expect(store.confirm(c)).rejects.toThrow(/正文/); c.mappings.body='invented'; await expect(store.confirm(c)).rejects.toThrow(/已有/); }));
  it('rejects traversal IDs and corrupt persisted records', () => inStore(async (store,folder) => { await expect(store.get('../escape')).rejects.toThrow(); const p=await store.import(wordTemplateFixture(),'模板'); await store.confirm(confirmation(p)); await writeFile(join(folder,`${p.id}.json`),'{}'); await expect(new WordTemplateStore(folder).get(p.id)).rejects.toThrow(/损坏/); }));
  it('fails clearly for a corrupt library instead of hiding templates', () => inStore(async (store,folder) => { await store.list(); await writeFile(join(folder,'default.json'),'bad'); await expect(store.list()).rejects.toThrow(/损坏/); }));
});
